### ISSUE TITLE
No module named msg

### ISSUE THREAD

**Issue by Lorkes** [chrisl8/ArloBot#32]
Tried to run scripts from manualTests.txt but got an ImportError: No module named msg. Lubuntu 16.04, installed everything by using quick install script.

**Comment by vatbrain** [comment]
Hi. I recently had a similar problem. In my case, I was not getting a clean result from catkin_make due to some missing dependencies in the sweep_ros package.  I worked around it for now by deleting the sweep_ros directory and re-running catkin_make.  
You can also try running 
catkin_make -DCATKIN_WHITELIST_PACKAGES="arlobot_msgs"
to just build the arlobot_msgs package and see if that gets you any further. Just be sure to clear the whitelist later on if you do this by running
catkin_make -DCATKIN_WHITELIST_PACKAGES=""
There is a "ROS for Arlobot" Google Group you may want to check out.
Good Luck!

**Comment by Lorkes** [comment]
Thanks for help, I didn't delete the folder, just run 
catkin_make -DCATKIN_WHITELIST_PACKAGES="arlobot_msgs"
and now I'm not getting that error, so I'm closing this issue
